### PR TITLE
Document stripesDeps

### PR DESCRIPTION
**Pull request by skomorokh**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
I would like to get this merged: @skomorokh, any thoughts on my comments above?

**Comment by skomorokh** [comment]
I agree that is worth clarifying: it is explicitly for gathering resources from NPM dependencies that are NOT otherwise Stripes modules explicitly included by the tenant.

But I'm trying to focus on other things at the moment so have yet to formulate a re-wording.

**Comment by MikeTaylor** [comment]
Fair enough. How's this?

* `stripesDeps` -- an array declaring the NPM package names of any UI-side dependencies of this module that Stripes needs to gather resources from. Currently these include: icons and translations.

**Comment by skomorokh** [comment]
Ok, I guess you're really determined to do this now. That reads a bit awkwardly. I think "package names" makes it more confusing as "does the package name include the namespace?" comes to mind (stripesDeps does). And "UI-side" is redundant; all NPM dependencies are UI-side. What if we just change it from:
> an array declaring any dependencies of this module that Stripes needs to gather resources from

to

> an array declaring any NPM dependencies of this module that Stripes needs to gather resources from

Which hopefully implies that you spell them the same way in the `stripesDep` array as in the `dependencies` property eg. including the namespace. Though I suppose we could call that out explicitly in a parenthetical?

**Comment by MikeTaylor** [comment]
Looks good to me!

(The reason I want this done is because Ethan needed exactly this functionality today, but the documentation didn't include it.)

**Pull request merged**
