### PR TITLE
Add routing guidelines to dev guide STRIPES-615

### PR DESCRIPTION
**Pull request by skomorokh**

### CODE REVIEW

**Comment by doytch** [comment]
This was pretty easy to read and helpful. I have one question though; want to make sure I'm reading it correctly.

One of the most common annoyances I have with the current routing and SAS setup is fetching and passing around an array of dropdown values. E.g., patron groups. They're

1. Available as a filter.
1. Shown as a column.
1. Used to translate the value on a user record (e.g., `ad0bc554-d5bc-463c-85d1-5562127ae91b`) to something human readable.
1. Available as dropdown options in the Create/Edit pages.

So let's assume: 
1. We move all the fetching of patron groups to the top-level route since it's used everywhere.
1. We're going to have a `/users` route that renders a `SearchAndSortQuery`.
1. We want separate routes for viewing (`/users/:{id}`), creating (`/users/create`), and editing (`/users/:{id}/edit`) a record, rather than `layer`s.

I'm having difficult figuring out how would we pass the `resources.patronGroups` data down to those CRUD routes. From what I understand:
1. The `Route` that creates the `/users` route would fetch the patron groups.
1. There would be nested, child routes for the CRUD routes.
1. The top-level `/users` route would use that stripes-core wrapper from `Route` and pass the patron groups data down to whatever `children` it was passed.

Is that right?

**Comment by skomorokh** [comment]
So the components pointed at by the CRUD routes are still entitled to play with glue since they're route handlers. It'd make sense for each of them to fetch the patron group list and for the service providing it to set appropriate cache headers and this way the back end can determine how stale of a patron group list we're willing to accept.

Of course, our present reality is such that we don't have such caching. And our data access methods will change anyway. So you want to fetch it in your top level route handler and pass it into its children. I ...don't know that there is a mechanism to pass props to children. I think that's something that was glibly elided in our discussions so far and is a key distinction between nesting routes in the index and actually nesting them.

One way to handle it would be to stash them in a context that we nest the children under. Hooks make that particularly easy to get at. Or a local resource if we want to keep it between app switches. But is this really how we want to roll? Does `/users/:{id}` need to put the current record into a `CurrentUser` context provider so that `/users/:{id}/edit` can populate the form with the current values rather than just nesting the route so we can pass it in as a prop? Or should the edit page independently fetch the user record?

Based on the eHoldings module, it seems like FrontSide intends that we would fetch it explicitly in each consuming route:
https://github.com/folio-org/ui-eholdings/blob/master/src/routes/title-edit.js#L220

Hm.

**Comment by doytch** [comment]
Yeah you've hit the issue. 

I don't think it's acceptable to not support app switches since I'm fairly certain it'll break down at some point because of things like dirty forms and reinitialisation. Also, the process of switching between apps will start getting a little slow and chuggy as we once again fetch all the data and deal with the process of rerendering/reflowing the page.

I think if we want to define all routes in index.js, we kinda back ourselves into a corner of _having_ to use something wide-ranging like what stripes-connect local resources are or going out to redux like Frontside did.

@JohnC-80 , have you had any thoughts about how you want to approach this with ui-users?

**Comment by JohnC-80** [comment]
I'm not sure of an initial plan of attack - ideally we can preserve user experience by doing a better job with skeleton loading if it's the worst case of always fetching data within detail views.
If its terrible, there could possibly be something we could work out with context/session storage... but that's a dragon to be slayed once we get there.
It's all hopefully a good trade for an ideally more maintainable code base and a far more accessible DOM.

**Comment by doytch** [comment]
@JohnC-80 On a separate note regarding the more accessible DOM, that'd fall out from this effort by ditching `<Layer>` overuse, right? If so, wouldn't we accomplish the same thing if we just selectively render `<Pane>`s? eg,  `return this.pathIsEdit() ? this.renderEditPane() : this.renderViewPane();`

I was just looking at Layer usage today and I realised that I don't really know why we render edit Panes in a Layer instead of just rendering the Pane itself.

**Comment by skomorokh** [comment]
> do we currently have a plan?

Of course not @doytch, caching is one of the many things being held in limbo while we await a green light on a gradual Apollo migration or stripes-connect overhaul. Doesn't really matter though--regardless if it's apollo or connect, and if the cache expiry is mediated by the front end or back, it's still the case that the data access layer should handle it and you should just be able to say "get the list of patron groups" without needing to explicitly stash it in context or something.

> eg, `return this.pathIsEdit() ? this.renderEditPane() : this.renderViewPane();`

Except of course you'd just render your children and the children would depend on the routes for view and edit you set up in index.js. The big change in this new more constrained model that I'm still not fully comfortable with is that you can't pass them props; essentially every component that you assign a route to needs to gather its own data in isolation from its parent with sharing being done explicitly via context/redux.

**Comment by doytch** [comment]
> The big change in this new more constrained model that I'm still not fully comfortable with is that you can't pass them props; essentially every component that you assign a route to needs to gather its own data in isolation from its parent with sharing being done explicitly via context/redux.

Texas-sized 10-4.

So I'm not really sure how we should move forward given that. It feels like we need to solve that issue to a degree we're at least mildly comfortable with before we start pushing these routing guidelines. Am I right or am I being too cautious?

**Comment by skomorokh** [comment]
That's why I haven't merged it yet :) But am starting to come around as we have moderated the language to _prefer_ this approach rather than strictly mandating it. So if a nested route works best, that's fine. In absence of a compelling reason not to, keep things decoupled and routed at the top. Talking a bit about this with John yesterday also. What do you think @JohnC-80, should we still be full steam ahead on this approach to app structure? In some ways you're more completely in this with your work refactoring users/s&s and having been present for more of the discussion that led up to it.

This thread about caching is quite relevant since, really, most things aren't coupled to local state and instead are just relying on data persisted remotely so it's actually kind of clearer if each route-handling component just describes up front what it needs rather than getting it via more circuituous means that make it trickier to move around later. Clearer, but unless we have caching, slower. Ultimately we do need caching of some sort though right?

**Comment by JohnC-80** [comment]
I guess its a good examination of *just how dependent some of these nested routes have to be to their parents as far as passing in props. I could understand with edit views... but there are also separate workflow paths like loans and fees/fines where nothing is really necessary aside from the count that's rendered in the preview pane.
Brainstorming up for experimentation and not completely advised yet: 
I believe the child routes will get inserted with a `props.children` render within the passed `component` prop....
A parent can possibly pass information into a child component via a context provider since those work hierarchically...
```
<ViewUserRoute>
  <UserRecord.Provider value ={ initialValues: initialValues } />
    {this.props.children (editUserRoute)}
  </UserRecord.Provider>
</ViewUser>
```

**Pull request merged**
